app:
  id: user-center

server:
  port: 8080

logging:
  config: classpath:logback.xml

spring:
  datasource:
    url: jdbc:mysql://172.16.85.126/my-test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: ydhx
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/

jetcache:
  statIntervalMinutes: 1 #统计间隔
  areaInCacheName: false
  local:
    default: #默认area
      type: caffeine
      keyConvertor: fastjson
  remote:
    default:
      type: redis.lettuce #使用lettuce
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 1
        maxIdle: 50
        maxTotal: 1000
        maxWait: 1000
      # uri: ['redis://password@192.168.14.231:6379/0','redis://password@192.168.14.232:6379/0','redis://password@192.168.14.233:6379/0']
      uri:
        - redis://127.0.0.1:6379/5  #redis://密码@IP:端口/库
      readFrom: masterPreferred #master优先

mybatis-plus:
  type-aliases-package: com.zhuhong.user.entity
  mapper-locations: classpath:/mybatis-mappers/*
  # 开启sql打印
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

create:
  name: zhuhong

